### ISSUE TITLE
Error in links[[i]] : subscript out of bounds

### ISSUE THREAD

**Issue by morelandjs** [papagorgio23/VegasLines#1]
Getting this error when trying to pull NFL lines 2009 through present. I don't know R very well. Any idea what might be causing this? Love the module!

**Comment by papagorgio23** [comment]
Unfortunately, Covers decided to redesign their website within the last week or so breaking all of my code...I'm a little annoyed because I updated this function to include MLB, NCAAF, NCAAB but now nothing works. I am hoping to have time to fix it over the next month but I created a little hack to get you what you want. I will add the data for NFL 2009-2019 Lines.

**Comment by morelandjs** [comment]
Awesome, thanks!
